# -*- coding: utf-8 -*-
"""RNN_email_flaskapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z85_cBTf73BEbT8bTPDHQAK_m45i2Poz
"""

nltk.download('stopwords')

app = Flask(__name__)

# Load tokenizer and model
with open("/content/drive/MyDrive/tokenizer.json", "r") as json_file:
    tokenizer_json = json_file.read()
tokenizer = tokenizer_from_json(tokenizer_json)



model = load_model("/content/drive/MyDrive/email_classification_model.h5")

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/Dataset.csv", header=None)

# Renaming columns
df.columns = ['email_type', 'content']

# Check for invalid label values
invalid_labels = df[~df['email_type'].isin(range(1, 19))]
if not invalid_labels.empty:
    print("Invalid label values found:")
    print(invalid_labels)

# Remove rows with invalid label values
df = df[df['email_type'].isin(range(1, 19))]

# Data preprocessing
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)  # Remove URLs
    text = re.sub(r'<.*?>', '', text)  # Remove HTML tags
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # Remove special characters (retain numbers)
    text = ' '.join([word for word in text.split() if word not in stopwords.words('english')])  # Remove stopwords
    return text

df['content'] = df['content'].apply(preprocess_text)

# Tokenization and Padding
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['content'])
X_seq = tokenizer.texts_to_sequences(df['content'])
max_length = 500
X_pad = pad_sequences(X_seq, maxlen=max_length, padding='post')

# Update labels
y = df['email_type'].values - 1  # Convert labels to 0-based indices

# Define the model
embedding_dim = 300
vocab_size = len(tokenizer.word_index) + 1

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim))
model.add(Bidirectional(LSTM(128)))
model.add(Dropout(0.5))
model.add(Dense(18, activation='softmax'))

# Compile the model
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss}, Test Accuracy: {accuracy}")

# Save tokenizer and model
model.save("email_classification_model.h5")
tokenizer_json = tokenizer.to_json()
with open("tokenizer.json", "w") as json_file:
    json_file.write(tokenizer_json)